repository: thompsonalt/thompsonalt.github.io
title: adamt.tv
author: Adam Thompson
description: VFX Artist / Tool Developer

# Build settings
markdown: kramdown

kramdown:
    input: GFM
    syntax_highlighter: rouge
